### ISSUE TITLE
TantivyIndex re-export gated on lexical-tantivy breaks consumers using the lexical feature (E0432)

### ISSUE THREAD

**Issue by JYeswak** [Dicklesworthstone/frankensearch#29]
Enabling only the `lexical` feature no longer re-exports `TantivyIndex`, so downstream crates that depend on `frankensearch/lexical` fail with `E0432: unresolved import frankensearch::TantivyIndex`.

## What changed

`frankensearch/src/lib.rs`:

```rust
// ─── Feature-gated lexical re-exports ───────────────────────────────────────

#[cfg(feature = "lexical-tantivy")]
pub use frankensearch_lexical::TantivyIndex;
```

`frankensearch/Cargo.toml`:

```toml
lexical = ["dep:frankensearch-lexical"]
lexical-tantivy = ["lexical"]
```

The dependency runs `lexical-tantivy -> lexical`, not the reverse. So `features = ["lexical"]` pulls in the `frankensearch-lexical` dep but leaves the `TantivyIndex` re-export cfg'd out. The type is still there (`frankensearch-lexical/src/lib.rs:662`) — only the facade re-export is gated behind the narrower feature.

Bisected to the quill integration flip (`f498cdd1`, 2026-07-23, "feat(quill): port facade index builder"). Pinning to `2e325206` (2026-07-23, immediately pre-flip) restores the build.

## Downstream impact

`eidetic_engine_cli` at `919caaf7` declares:

```toml
lexical-bm25 = ["frankensearch/lexical"]
```

and `lexical-bm25` is in its default feature set, so a default `cargo build` of ee against frankensearch `main` fails to compile.

## Question rather than assumption

Is this intended — i.e. should consumers wanting `TantivyIndex` now request `lexical-tantivy` explicitly (in which case ee's `lexical-bm25` mapping needs updating and this is a documentation/migration note) — or should the `lexical` feature continue to re-export it during the quill transition?

Happy to send a PR either way once you confirm the intended direction. If it's the former, the ee-side fix is a one-line feature remap and I can file that upstream too.

Environment: macOS 15 (Darwin 25.5.0), arm64, stable toolchain. Not blocking us — we have a working pin at `2e325206`.

**Comment by Dicklesworthstone** [comment]
Intended — and thanks for asking rather than assuming. Post-flip, `lexical` means "pull in the pre-flip Tantivy crate" and `lexical-tantivy` is the explicit oracle/migration surface, which is what the facade re-export is now gated on (lib.rs:338). So `frankensearch/lexical-tantivy` is the right ask for ee's lexical-bm25.

If you'd rather not widen the feature: `frankensearch::lexical::TantivyIndex` still resolves under plain `lexical` via the module alias at lib.rs:201.

What's missing is the migration note — the README describes the lane but the CHANGELOG never called out the narrowing. That one's on me. Closing as intended behavior; the CHANGELOG gets the migration line.
